media:
  input: src/assets
  output: ../../assets

content:
  - name: about
    label: About page
    path: src/content/info/about.md
    type: file
    fields:
      - name: body
        label: Body
        type: rich-text
  
  - name: description
    label: Description
    path: src/content/info/description.md
    type: file
    fields:
      - name: body
        label: Body
        type: rich-text
  
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    filename: '{primary}.md'
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Creation date
        type: date
        options:
          format: MMM dd yyyy
          min: 2023-12-24
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body
        type: rich-text
